
binary_sensor:
  - platform: mqtt
    state_topic: dummy/binary_sensor
    name: Floorplan

  - platform: mqtt
    state_topic: floorplan/kiosk/entry/motion
    name: Entry Kiosk Motion
    retain: true

  - platform: mqtt
    state_topic: floorplan/kiosk/entry/plugged
    name: Entry Kiosk Plugged
    retain: true

  - platform: mqtt
    state_topic: floorplan/kiosk/bedroom/motion
    name: Bedroom Kiosk Motion
    retain: true

  - platform: mqtt
    state_topic: floorplan/kiosk/bedroom/plugged
    name: Bedroom Kiosk Plugged
    retain: true

media_player:
  - platform: floorplan_speaker
    name: Entry Kiosk

  - platform: floorplan_speaker
    name: Bedroom Kiosk

